const SESSION_STATUS = {
  CLIENT_ENDED: 'CLIENT_ENDED',
  AGENT_BUSY: 'AGENT_BUSY',
  AGENT_ENDED: 'AGENT_ENDED',
  AGENT_DECLINED: 'AGENT_DECLINED',
  UNAVAILABLE_DEVICE: 'UNAVAILABLE_DEVICE',
  AGENT_DISCONNECTED: 'AGENT_DISCONNECTED',
  CLIENT_DISCONNECTED: 'CLIENT_DISCONNECTED',
};

module.exports = {
  SESSION_STATUS,
};
