const MODULES_MAP = {
  CALLS: 'hasCalls',
};

const ENTITY_STATUS = {
  ACTIVE: 'ACTIVE',
  DEACTIVE: 'DEACTIVE',
};

const ENTITY_ORIGIN = {
  CRM: 'CRM',
  APP: 'APP',
  VW_FREE_TRIAL_WP: 'VW_FREE_TRIAL_WP',
  QUAL_DEMO_WP: 'QUAL_DEMO_WP',
  QUAL_FREE_TRIAL_PRO_WP: 'QUAL_FREE_TRIAL_PRO_WP',
  QUAL_FREE_TRIAL_ADVANCED_WP: 'QUAL_FREE_TRIAL_ADVANCED_WP',
};

const DEFAULT_MODULES = {
  hasCalls: false,
};

const ENTITY_EMAIL_TYPE = {
  CHECK_SCRIPT_INSTALLATION: 'CHECK_SCRIPT_INSTALLATION',
  CHECK_ONE_WEEK_INTERACTION: 'CHECK_ONE_WEEK_INTERACTION',
};

module.exports = {
  MODULES_MAP,
  ENTITY_STATUS,
  ENTITY_ORIGIN,
  DEFAULT_MODULES,
  ENTITY_EMAIL_TYPE,
};
