const REGISTRY_TYPE = {
  ACCESS: 'ACCESS',
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  CALL_MISSED: 'CALL_MISSED',
  CALL_DECLINED: 'CALL_DECLINED',
  CALL_ACCEPTED: 'CALL_ACCEPTED',
  CALL_FINISHED: 'CALL_FINISHED',
  CALL_REQUESTED: 'CALL_REQUESTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  CALL_FINISHED_FORCED: 'CALL_FINISHED_FORCED',
  USER_DISCONNECTED_ON_CALL: 'USER_DISCONNECTED_ON_CALL',
  CLIENT_DISCONNECTED_ON_CALL: 'CLIENT_DISCONNECTED_ON_CALL',
};

module.exports = {
  REGISTRY_TYPE,
};
